### ISSUE TITLE
Angular 2?

### ISSUE THREAD

**Issue by MateuszG** [GreenfieldVentures/angular-on-screen-keyboard#2]
Will you support new version?

**Comment by meleath** [comment]
New version as in Angular2/4 or 1.6?

**Comment by meleath** [comment]
Sorry, I just now saw the

**Comment by meleath** [comment]
Sorry, at this point we don't plan to rewrite the plugin for angular 2. It would be a new git repo in any case but it be happy to help you along the way if you're interested in spear heading the development
