### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by KarlFS** [GreenfieldVentures/angular-on-screen-keyboard#3]
Hello, seems that Firefox is sending another kind of events, so that the keyboard is not triggered!?

Kind regards, 

Karl

**Comment by meleath** [comment]
Do you have the possibility to make a pull request with suggested changes/fixes?

**Comment by KarlFS** [comment]
I will test my changes this week and make a pull request after testing!

**Comment by KarlFS** [comment]
Ok, seems not to work. But there is a solution for the specific applications, so possibly you should describe how to use this:

https://gist.github.com/nuxodin/9250e56a3ce6c0446efa

**Comment by meleath** [comment]
Thank you for your help and research! I'll include a link to the polyfil in the readme. Much appreciated
