### ISSUE TITLE
Language support?

### ISSUE THREAD

**Issue by lilo12** [GreenfieldVentures/angular-on-screen-keyboard#4]
Hi,

just wondering if this supports different languages?

**Comment by meleath** [comment]
The keyboard itself is fully customizable ...at least to some extent. There's no plugin model with different keyboard configurations, but such a model would not be to hard to create. Could you please be more specific as to what you're looking for/missing?

**Comment by jackwarm** [comment]
Is angular-on-screen-keyboard designed for Angular 1 or Angular 4?

**Comment by meleath** [comment]
Angular 1
