### ISSUE TITLE
Letter/Characters appending to the left of input instead of right 

### ISSUE THREAD

**Issue by ray-man** [GreenfieldVentures/angular-on-screen-keyboard#5]
Using the keyboard appends character to the left of input string, say typing 01234 by using this module will result 43210 on input field, any fix or other way around to it?

**Comment by ray-man** [comment]
@meleath , @joelfransson  anything regarding this issue ?

**Comment by meleath** [comment]
Looking into it today or tomorrow. Seems to be a fresh "feature" in chrome that I didn't know about.

**Comment by meleath** [comment]
Try now with version 0.9.7

**Comment by meleath** [comment]
Can I close this issue?

**Comment by ray-man** [comment]
Thanks it works fine now.
