### ISSUE TITLE
Update bower version please :)

### ISSUE THREAD

**Issue by luismiguelprs** [GreenfieldVentures/angular-on-screen-keyboard#6]
Can you publish the new version to bower? Thanks!

**Comment by meleath** [comment]
That's not how Bower works. There's no publishing involved. What version is specified in your package.json and have you tried clearing bower's cache?

**Comment by luismiguelprs** [comment]
yes :( but the version there is the 0.9.2... I've tried to force 0.9.6 or 0.9.7 and it didn't install...

**Comment by meleath** [comment]
My bad. I forgot to update the tags which is required for bower to pick up on changes. Done now. Hope it helps.

**Comment by luismiguelprs** [comment]
Yeah! Thanks! :+1:

**Comment by meleath** [comment]
Awesome! Happy to help
