### ISSUE TITLE
Uncaught Error: [$rootScope:inprog] after Keyboard click

### ISSUE THREAD

**Issue by athanasius-kircher** [GreenfieldVentures/angular-on-screen-keyboard#7]
If I click a key on the keyboard in Demo 2 it triggers a javascript error. The Value is inserted in the field and the functionality does not seem to be effected.

The change: 644e20c03502f9953ed6fc58553b0391076d2863, seems to have introduced this problem described under: https://docs.angularjs.org/error/$rootScope/inprog?p0=$apply. The call to `ctrl.refocus();` in a directive leads to an inner $digest call.

**Comment by meleath** [comment]
Nice catch! Unfortunately I won't be able to look into this for a other week. I'd be very happy to take a PR though if you want and have the time.

**Comment by meleath** [comment]
Try 0.9.8
