### ISSUE TITLE
Wrapper for Angular 2+

### ISSUE THREAD

**Issue by benmed00** [GreenfieldVentures/angular-on-screen-keyboard#8]
Hi, 
i have an angular 4 need for the same essue 

can you help me

**Comment by meleath** [comment]
I’d be happy to help you co-write such a plug-in for angular, but unfortunately I don’t have to time right now to port this myself.

**Comment by benmed00** [comment]
ok, thanks for the replay

2018-04-17 8:59 GMT+01:00 Jacob Blecher <notifications@github.com>:
